services:
  - type: web
    name: mini-social-api
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: RUN_MIGRATIONS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: mini-social-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: COOKIE_SECURE
        value: true

databases:
  - name: mini-social-db
    databaseName: minisocial
    user: postgres
    plan: free
    region: oregon
